apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-extra-config
data:
  ENV_VAR1: value1
  application.properties: |
    server.port=8080
    logging.level.root=INFO

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-extra-env
data:
  SERVER_PORT: "8080"
  LOGGING_LEVEL_ROOT: "INFO"
