apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "springboot-parameters.fullname" . }}
  labels:
    {{- include "springboot-parameters.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "springboot-parameters.selectorLabels" . | nindent 6 }}
      app: {{ .Chart.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "springboot-parameters.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: {{ .Chart.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: externalsecrets-aws
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: cm-extra-env
            - secretRef:
                name: secret-extra-env
          env:
            - name: ENV_VAR5
              valueFrom:
                secretKeyRef:
                  name: springboot-parameters
                  key: ENV_VAR5
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: ENV_VAR1
              valueFrom:
                configMapKeyRef:
                  name: cm-extra-config
                  key: ENV_VAR1
            - name: ENV_VAR4
              valueFrom:
                secretKeyRef:
                  name: secret-extra-config
                  key: ENV_VAR4
          volumeMounts:
            - name: ps-volume
              readOnly: true
              mountPath: /ps-config
            - name: configmap-volume
              readOnly: true
              mountPath: /config

            - name: secret-volume
              readOnly: true
              mountPath: /secret-config
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: ps-volume
          secret:
            secretName: springboot-parameters
            items:
              - key: application.secret.properties.from.ps
                path: application.secret.properties.from.ps
        - name: configmap-volume
          configMap:
            name: cm-extra-config
            items:
              - key: application.properties
                path: application.properties

        - name: secret-volume
          secret:
            secretName: secret-extra-config
            items:
              - key: application.secret.properties
                path: application.secret.properties
