apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "springboot-parameters.fullname" . }}
  labels:
    {{- include "springboot-parameters.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "springboot-parameters.selectorLabels" . | nindent 6 }}
      app: {{ .Chart.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "springboot-parameters.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: {{ .Chart.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "springboot-parameters.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: CONFIG_PATH
              value: /config
            - name: SECRET_CONFIG_PATH
              value: /secret-config
            - name: ENV_VAR1
              valueFrom:
                configMapKeyRef:
                  name: cm-extra-config
                  key: ENV_VAR1
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: cm-extra-env
                  key: SERVER_PORT
            - name: LOGGING_LEVEL_ROOT
              valueFrom:
                configMapKeyRef:
                  name: cm-extra-env
                  key: LOGGING_LEVEL_ROOT
            - name: ENV_VAR4
              valueFrom:
                secretKeyRef:
                  name: secret-extra-config
                  key: ENV_VAR4
            - name: ENV_VAR2
              valueFrom:
                secretKeyRef:
                  name: secret-extra-env
                  key: ENV_VAR2
            - name: ENV_VAR3
              valueFrom:
                secretKeyRef:
                  name: secret-extra-env
                  key: ENV_VAR3
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: secret-volume
              mountPath: /secret-config
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: cm-extra-config
        - name: secret-volume
          secret:
            secretName: secret-extra-config
