apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: springboot-parameters
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-parameterstore
  data:
  - secretKey: ENV_VAR5
    remoteRef:
      key: krci-cmtr-647f9884-springboot-parameters
      property: springboot-parameters.ENV_VAR5
  - secretKey: application.secret.properties.from.ps
    remoteRef:
      key: krci-cmtr-647f9884-springboot-parameters
      property: springboot-parameters.config
      decodingStrategy: Base64
