---
apiVersion: v1
kind: Secret
metadata:
  name: secret-extra-config
type: Opaque
data:
  ENV_VAR4: dmFsdWU0Cg== # Base64 encoded value for "value4"
  application.secret.properties: |
    c2VjcmV0LnBhc3N3b3JkPXNlY3JldC1wYXNzd29yZAo= # Base64 encoded value for "secret.password=secret-password"

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-extra-env
type: Opaque
data:
  ENV_VAR2: dmFsdWUyCg== # Base64 encoded value for "value2"
  ENV_VAR3: dmFsdWUzCg== # Base64 encoded value for "value3"
