apiVersion: v1
kind: Secret
metadata:
  name: secret-extra-config
stringData:
  ENV_VAR4: value4
  application.secret.properties: |
    server.port=8080
    logging.level.root=INFO
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-extra-env
type: Opaque
stringData:
  ENV_VAR2: dmFsdWUyCg== # Base64 encoded value for "value2"
  ENV_VAR3: dmFsdWUzCg== # Base64 encoded value for "value3"
